name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        # os: [windows-large, linux-large]
        os: [linux-large]
        addrsize: ["64"]
        # include:
        #   - os: macos
        #     tag: self-hosted
        #     addrsize: "64"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 900
    steps:
      - name: Setup linux dependencies
        if: matrix.os == 'linux-large'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install gperf libcups2-dev python3-bs4 python3-html5lib libxkbcommon-x11-dev libgtkglext1-dev libnss3-dev libgtk-3-dev
      - uses: secondlife/action-autobuild@v3
        with:
          addrsize: ${{ matrix.addrsize }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v2
