name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-large]
        addrsize: ["64"]
        include:
          - os: macos-13-xlarge
            addrsize: "64"
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    timeout-minutes: 900
    steps:
      - uses: secondlife/action-autobuild@v3
        with:
          addrsize: ${{ matrix.addrsize }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v2
