name: Build
on: [push]
env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
jobs:
  build:
    strategy:
      matrix:
        os: [windows-large, macos-12-xl]
        addrsize: ["64"]
        include:
          - os: windows-large
            addrsize: "32"
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    timeout-minutes: 900
    steps:
      - uses: secondlife/action-autobuild@v3
        with:
          addrsize: ${{ matrix.addrsize }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v2
